// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const about: { "principles": Array<{ "heading": string; "body": string; "id": string }>; "channels": Array<{ "href": string; "label": string; "body": string; "id": string }> };
  export const ai_tech: { "services": Array<{ "title": string; "description": string; "id": string }> };
  export const collections: { "hero": { "eyebrow": string; "heading": string; "headingAccent": string; "subheading": string; "ctaPrimary": string; "ctaSecondary": string }; "manifesto": { "heading": string; "body": string }; "categoriesEyebrow": string; "categoriesHeading": string; "categories": Array<{ "label": string; "description": string; "id": string }>; "pillarsEyebrow": string; "pillarsHeading": string; "pillars": Array<{ "title": string; "description": string; "id": string }>; "imagePullQuote": string; "imagePullQuoteAccent": string; "ctaHeading": string; "ctaBody": string; "ctaPrimary": string; "ctaSecondary": string };
  export const contact: { "areas": Array<string> };
  export const home: { "hero": { "motto": string }; "nav": { "exploreLabel": string }; "channels": Array<{ "href": string; "navLabel": string; "label": string; "tagline": string; "description": string; "cta": string; "id": string }>; "mission": { "eyebrow": string; "heading": string; "body": string; "tagline": string }; "cta": { "eyebrow": string; "heading": string; "body": string; "primaryLabel": string; "secondaryLabel": string }; "sectionLabel": string; "sectionHeading": string };
  export const insight: { "products": Array<{ "name": string; "description": string; "status": string; "id": string }> };
}
